// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitleAttribute("BloombergProvider.Runtime")>]
[<assembly: AssemblyProductAttribute("BloombergProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing BloombergProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "BloombergProvider.Runtime"

    [<Literal>]
    let AssemblyProduct = "BloombergProvider"

    [<Literal>]
    let AssemblyDescription =
        "This library is for the .NET platform implementing BloombergProvider."

    [<Literal>]
    let AssemblyVersion = "1.0.0"

    [<Literal>]
    let AssemblyFileVersion = "1.0.0"
